### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by brijen1812** [Azure-Samples/active-directory-javascript-singlepageapp-angular#11]
I downloaded the code from your repository and ran it after performing the given steps. When I ran it, on console it is showing an error. It is not allowing to run the application.

I dig more into it to resolve the issue and I found that when I remove the dependency injection of MsalService from constructor of AppComponent, application was running perfectly. So my first observation is, it is not injecting the MsalService dependency in constructor. Please find the attached screenshot of error.

![image](https://user-images.githubusercontent.com/52993091/81320905-826bc980-90af-11ea-9e3d-156c50c39ddb.png)

**Comment by derisen** [comment]
hi @brijen1812 -could you share your configuration please? And check out this solution [here](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular/issues/8#issuecomment-623444159) to make sure your `authority` and `protectedResourceMap` configs.

**Comment by brijen1812** [comment]
Hi @derisen , I tried that solution provided by you over that link and it worked for me. Thank you very much for your help. We can close this issue.

Thanks Much Again for all the help.
