### ISSUE TITLE
Change configuration after production build

### ISSUE THREAD

**Issue by ninopetrovic** [Azure-Samples/active-directory-javascript-singlepageapp-angular#12]
Hello.

I didn't really know how to tittle this issue therefore the tittle probably isn't the best. So what my problem actually is, is that we have many clients (20+) and everyone of this companies will use our app but they will all have different apps on azure thus the different clientId... different redirectUrl because our app will run on their servers.. and different authority probably.

So the problem is that right now in my app.module.ts I have statically defined configuration for msal module. I don't know how I would change this configuration dynamically. For other settings we have a file "settings.js" in our assets folder which we replace when we deploy our app to our clients. But this method is impossible to use in modules I guess since it throws an error. 

![image](https://user-images.githubusercontent.com/43232121/82154461-6fef4e00-986e-11ea-8ae6-0953ca73dca4.png)

I know I could use environments for this... but having 20+ environments is just to much. This cannot be the only solution.

Do you have any other guidelines or solutions for this? I would be really thankful if anyone could help me put here.

Regards.

**Comment by jasonnutter** [comment]
@ninopetrovic Please see [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-angular/docs/configuration.md) for different strategies for configuring MSAL Angular, including dynamically.

**Comment by ninopetrovic** [comment]
Yes! this is what I needed. I couldn't find this part of documentation somehow.

For anyone else that might be interested in the follow up to my problem:
I modified my code to setup the configuration via "platformBrowserDynamic" option. Where the json file that contains settings is replaced every time our application is deployed to our client with a setting file that contains correct settings for this particular client.

Thanks again.
