### ISSUE TITLE
Access token is empty

### ISSUE THREAD

**Issue by JaroslawParadysz** [Azure-Samples/active-directory-javascript-singlepageapp-angular#21]
After logging in with me personal account and clicking on the profile link, I get the following error in the response:
```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-08-06T05:20:32",
      "request-id": "3d71ebc2-529e-40d0-9e83-e73f2aa60226"
    }
  }
}
```
It looks like MSALInterceptor do not attach an access token to the request. Have you had the same issue?

**Comment by derisen** [comment]
@JaroslawParadysz could you give us some info about how to reproduce this? Also, your MSAL-Angular configuration would be helpful here.

**Comment by JaroslawParadysz** [comment]
@derisen, thank you for your response.
Below is my configuration:
```
MsalModule.forRoot({
      auth: {
        clientId: 'myApplicationId...',
        authority: 'https://login.microsoftonline.com/common',
        redirectUri: 'http://localhost:4200',
      },
      cache: {
        cacheLocation: 'localStorage',
        storeAuthStateInCookie: isIE, // set to true for IE 11
      },
    }
```
![image](https://user-images.githubusercontent.com/19383797/89707797-dbc6eb80-d971-11ea-9790-ad47791eba21.png)

Steps to reproduce:
1. Start active-directory-javascript-singlepageapp-angular
2. Login by using personal Microsoft account


3. Click Profile link

The interceptor do not attach access token to the request, as a result I received 401.
![image](https://user-images.githubusercontent.com/19383797/89708539-7a564b00-d978-11ea-8b0e-570a47c6aa7f.png)

Do you need something else?
Thanks in advance :)

**Comment by JaroslawParadysz** [comment]
It was my fault, I forgot fill protectedResourceMap. Now it works like a charm :).
I have strong feeling that it should be stressed in the Setup section of the Readme file.

**Comment by derisen** [comment]
Glad you're issue solved : ) Good point, I'll update the readme. Leaving this open for now.
