### ISSUE TITLE
User ID 

### ISSUE THREAD

**Issue by baole** [Azure-Samples/active-directory-javascript-singlepageapp-angular#25]
I'm using this sample app with my own "client ID". I successfully logged in and get a UserID. At the same time, a bot I built with Bot Framework (https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0) also gives a UserID. Both IDs are from the same user. However, they are different. Could you please explain?

To be clear, I'm building a bot which has a companion web app. The companion web app helps users to configure their preferences and few other settings. In this specific use case, I would expect the UserID from the bot and the UserID from single sign in should be identical.

**Comment by derisen** [comment]
@baole it's not very clear what you mean by "UserID" -is that a Bot Framework specific property? Are you talking about [OID](https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims)? From where do you obtain this (from a claim in tokens, perhaps)? Also, please try to use the issue template next time, it gives us a better idea of what your environment is like.

**Comment by baole** [comment]
@derisen it's `profile.id` property in this example (https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-angular/blob/master/src/app/profile/profile.component.ts#L14) and `from.id` property from `membersAdded` Microsoft Teams event callback JSON payload (https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=json#team-members-added)

**Comment by derisen** [comment]
@baole thank you for your patience. The `profile` object returned by the sample is an [MS Graph API user resource](https://docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0)

> The unique identifier for the user. Should be treated as an opaque identifier. Inherited from [directoryObject](https://docs.microsoft.com/en-us/graph/api/resources/directoryobject?view=graph-rest-1.0). Key. Not nullable. Read-only.

While I don't have much knowledge on Azure Bot Service / Teams Service, it's possible that the IDs here are not related at all. To make sure, please direct your query to [MS Graph](https://developer.microsoft.com/en-us/graph) itself.

Closing, as no further action to take.
