### ISSUE TITLE
Access token null in the response

### ISSUE THREAD

**Issue by biraj195** [Azure-Samples/active-directory-javascript-singlepageapp-angular#32]
Hi,

I have pointed the source to my B2C environment and configured to display a sign-in user flow. After, successful sign-in , the response object has all the values like id_token, and some more.  But, the access token in the response is coming as null. So, what
needs to be done to get the access token.  

Thanks,

**Comment by derisen** [comment]
@biraj195 apologies for late response. Can you share your configuration and library version? If using msal.js 1.x, B2C service does not return an access token at first login; you should make a token request for a scope. Also, see the Angular 1.x B2C sample [here](https://github.com/Azure-Samples/active-directory-b2c-javascript-angular-spa).

**Comment by derisen** [comment]
Closing. Let us know if you need help.
