### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by rnkpareek** [Azure-Samples/active-directory-javascript-singlepageapp-angular#34]
can you please add the refresh token in your repo.
Because its difficult for developer to do R&D and meet the time line

**Comment by derisen** [comment]
@rnkpareek this sample is using [msal-angular v1](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/msal-angular-v1/lib/msal-angular) which acquires token with [implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow). As such, it does not involve refresh tokens.

For usage of refresh tokens, check out [this sample here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa), which is using [msal-angular v2](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) with [auth code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow). Be aware that the library handles refresh tokens by itself. You do not need to worry about them.

You might also find [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/token-lifetimes.md) useful.

**Comment by rnkpareek** [comment]
i used B2c and i was able to get the refreshToken which is IdToken and i used to replace the same in localstorage and same i use to pass in http headers  and my backed api use to validate the exp time of token, but while using this lib iam able to get the new access token but the idToken is not changed which again throws used out of the application.
Can you guide me.

**Comment by derisen** [comment]
@rnkpareek The Id token is not a refresh token, and in general you do not need to worry about refresh tokens as the library handles refreshing tokens by itself. You definitely shouldn't get tokes from localstorage, MSAL has APIs for retrieving that. I'm not sure what's your goal here, can you elaborate?

**Comment by rnkpareek** [comment]
let me explain you the problem:
Iam using the msal lib for login-in >Once user is logged in the id token is being stored in local storage >I use to pass the ID token in api to validate the user .
The id token have the exp time of 1 hour, if i don't refresh the ID token my api use to check the exp time of token so the application become dead and user is logged out.
I just need to get new id Token just before the id token gets expire.

**Comment by derisen** [comment]
I see. So what is recommended in this case is to silently renew the tokens just before calling your web API and sending them over. This makes sure that the tokens you send are valid at the time of sending (see the [FAQ](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-core/docs/FAQ.md#how-do-i-renew-tokens-with-msaljs)). In fact, this is how this sample works under the hood. So for example (in vanilla JavaScript):

```javascript
function getTokenPopup(request) {
  return myMSALObj.acquireTokenSilent(request)
    .catch(error => {
      console.log("silent token acquisition fails. acquiring token using popup");
          
        // fallback to interaction when silent call fails
        return myMSALObj.acquireTokenPopup(request)
          .then(tokenResponse => {
            return tokenResponse;
          }).catch(error => {
            console.log(error);
          });
    });
}

function callMyAPI() {
    getTokenPopup()
      .then(response => {
        callApiWithToken(endpoint, response.accessToken, callback);
      }).catch(error => {
        console.log(error);
      });
}
```

I also would recommend using [msal-angular v2](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/lib/msal-angular) as it acquires token using auth code flow. Tokens acquired as such have a longer expiry time (ID and refresh tokens 24 hr, access token 1 hr). You can find a sample [here](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa).

**Comment by rnkpareek** [comment]
i have tried it too ,
but while using  msal-angular v2  "getAccount()"  method  gives error and the token is not being refreshed.
There is something really wrong in this lib, while using "acquireTokenSilent "  the access token nor the "idToken" is being refreshed  which is a big problem because we need this .

**Comment by rnkpareek** [comment]
can you suggest something practical that really works in angular way h=just need to refresh the "IdToken"
What shall i pass in acquireTokenSilent() as parameter and what admin access should  be given from azure ad side.
Simple.

**Comment by derisen** [comment]
@rnkpareek you need to supply an `account` object when using the `acquireTokenSilent()`. `getAccount()` is replaced with `getAllAccounts()`, `getAccountByUsername()`... etc. in **msal-angular-v2** (see: [docs](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/accounts.md)), so that's why you are not able to get the current account.

I saw you open a [new issue](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/2962) in main MSAL.js repo. I'll close this as duplicate then. Please understand that you need to fill out the issue template we set up when you create an issue. This gives us the relevant details with your scenario and tech stack, the library versions you use and etc. Without this, it will take longer to understand your problem and offer a solution.
