### ISSUE TITLE
Error after all steps and successful compile

### ISSUE THREAD

**Issue by ninopetrovic** [Azure-Samples/active-directory-javascript-singlepageapp-angular#8]
![image](https://user-images.githubusercontent.com/43232121/80475959-04d6e980-894a-11ea-86c7-5b224b8aa8e2.png)

After all these steps and a successful compile, when I navigate to the page it is blank and this error is present in the console:
![image](https://user-images.githubusercontent.com/43232121/80476207-597a6480-894a-11ea-9df1-ccce99edd5c4.png)

**Comment by ttandel1** [comment]
same issue i am also facing.
![image](https://user-images.githubusercontent.com/25515819/80933322-3d832280-8d91-11ea-8c22-a82a8f49f699.png)

**Comment by mickyc1** [comment]
Also have the same issue.

double checked, client id, app id, implicit flow and user.read api permission is setup correctly. Any help would be greatly appreciated

**Comment by ninopetrovic** [comment]
I managed to resolve this issue. In short there was something wrong with my setup.

Things to make sure:
If your app is not multi tenant. you should replace the "common" with your tenant id
![image](https://user-images.githubusercontent.com/43232121/80967062-0b67d400-8e16-11ea-872d-eecbf9530cc1.png)

make sure your redirect url match and that the protected resource map looks like this
![image](https://user-images.githubusercontent.com/43232121/80967294-6699c680-8e16-11ea-9ad0-a80c8204ae69.png)

**Comment by mickyc1** [comment]
Brilliant @ninopetrovic that sorted it for me!

**Comment by derisen** [comment]
Sorry for missing this -and thanks @ninopetrovic ! I take it the issue is resolved? We will add a clarification about this to the readme.

**Comment by ninopetrovic** [comment]
I am glad to hear this @mickyc1 👍.

I will close this issue since it worked for at least two of us. Hope others find it helpful as well.

**Comment by ninopetrovic** [comment]
@derisen yes you can mark it as resolved. And no problem It didn't take to long to get around.
